name: ical
version: 0.3.0
description: >-
  A library to generate/serialize iCalendar files
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.12.0
  intl: ^0.19.0
  nanoid: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: any
