name: ical
version: 0.1.1
description: >-
  A library to generate/serialize iCalendar files
author: Lukas Himsel <lukas@himsel.me>
homepage: https://github.com/dartclub/ical

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  intl: ^0.16.0
  nanoid: ^0.1.0

dev_dependencies:
  test: ^1.5.1+1
  pedantic: ^1.8.0

